SELECT * FROM SP_CONTENTS;
SELECT * FROM SP_PLATFORM;
SELECT * FROM REVIEW;
SELECT * FROM USERTB;
SELECT * FROM WISHLIST;

select * from user_sequences;
                  
SELECT MAX(MovieNum) FROM SP_PLATFORM WHERE PFCODE IN 'WC';
SELECT MovieNum FROM SP_CONTENTS SC WHERE SC.MovieNum > 2;

SELECT COUNT(*) FROM USERTB WHERE ID = 'RT' AND NAME = 'hello' AND EMAIL = 'wnehdwlswn@naver.com';

DELETE FROM USERTB WHERE NAME = '동동주';
SELECT IMGURL FROM USERTB WHERE NAME = '동동주';