SELECT * FROM SP_CONTENTS;
SELECT * FROM SP_PLATFORM;
SELECT * FROM REVIEW;
SELECT * FROM USERTB;
SELECT * FROM WISHLIST;
SELECT * FROM NOTIFICATION;
SELECT * FROM CONTENTS;
SELECT * FROM PlatForm;
SELECT * FROM PlatFormCode;

select * from user_sequences;
                  
SELECT MAX(MovieNum) FROM SP_PLATFORM WHERE PFCODE IN 'WC';
SELECT MovieNum FROM SP_CONTENTS SC WHERE SC.MovieNum > 2;

SELECT COUNT(*) FROM USERTB WHERE ID = 'RT' AND NAME = 'hello' AND EMAIL = 'wnehdwlswn@naver.com';

DELETE FROM CONTENTS WHERE MOVIENUM = 124;
DELETE FROM PLATFORM WHERE PFCODE = 'WV';
SELECT * FROM USERTB WHERE NAME = '주동진';

INSERT INTO NOTIFICATION VALUES ( ALARM_SQ.NEXTVAL, 34, '알람 내용4', 'F', SYSDATE );

INSERT INTO CONTENTS VALUES (MOVIE_SQ.NEXTVAL, 'Test', '2020', '홍길동', '춘향이', 5.5, '액션', '춘향이와 홍길동의...ㅎㅎ..', '주소1', SYSDATE, '주소2' );	
INSERT INTO PLATFORM VALUES ('WV', 92);

SELECT MOVIE_SQ.NEXTVAL-2 FROM DUAL;   <-- 90 91 92 93-->


CREATE OR REPLACE TRIGGER PLATFORM_UPDATE

AFTER INSERT ON CONTENTS
FOR EACH ROW

BEGIN
	IF INSERTING THEN
		INSERT INTO PLATFORM VALUES ('WV', MOVIE_SQ.NEXTAL-1);
	END IF;
END;